#Encoding: UTF-8
#This is the main configuration file for the OpenRubyRMK. 
--- 
#The locale you want the GUI to be displayed in. 
#If this is set to "auto" (without the quotes), the language 
#will be detected automatically from your OS setup. 
#Default value: auto
locale: en
#This is the Ruby installation that will be used for editing 
#games with OpenRubyRMK. If you choose your own installation, 
#make sure it's 1.9 and has the "gosu" and "chingu" gems installed. 
#Examples: 
#  ruby: "/home/freak/myruby/bin"
#  ruby: "C:\myruby\bin"
#Default value: auto
ruby: "/opt/rubies/ruby-1.9.1-p429/bin"
