#Encoding: UTF-8
#This is the main configuration file for the OpenRubyRMK. 
--- 
#The locale you want the GUI to be displayed in. 
#If this is set to "auto" (without the quotes), the language 
#will be detected automatically from your OS setup. 
#Default value: auto
locale: en
